MD_FILENAMES = [
    "abbr-currency-symbols",
    "abbr-emoji",
    "abbr-natural-language-codes",
    "abbr-prefixes",
    "abbr-programming-language-codes",
    "abbr-single-character",
    "abbr-starts-with-a",
    "abbr-starts-with-b",
    "abbr-starts-with-c",
    "abbr-starts-with-d",
    "abbr-starts-with-digits",
    "abbr-starts-with-e",
    "abbr-starts-with-f",
    "abbr-starts-with-g",
    "abbr-starts-with-h",
    "abbr-starts-with-i",
    "abbr-starts-with-k",
    "abbr-starts-with-l",
    "abbr-starts-with-m",
    "abbr-starts-with-n",
    "abbr-starts-with-non-alphanumeric",
    "abbr-starts-with-o",
    "abbr-starts-with-p",
    "abbr-starts-with-q",
    "abbr-starts-with-r",
    "abbr-starts-with-s",
    "abbr-starts-with-t",
    "abbr-starts-with-u",
    "abbr-starts-with-v",
    "abbr-starts-with-w",
    "abbr-starts-with-x",
    "abbr-starts-with-y",
    "abbr-suffixes",
    "abbr-symbols",
    "abbr-units-of-measure",
    "annotation-markers",
    "chat",
    "coder-bash",
    "coder-c",
    "coder-c-sharp",
    "coder-cpp",
    "coder-gdscript",
    "coder-html",
    "coder-javascript-and-typescript",
    "coder-python",
    "coder-python-docstring-style",
    "coder-python-testing-guidelines",
    "coder-unity-engine",
    "coder-unreal-engine",
    "date-and-time-format",
    "kaye-peer-coder",
    "numerical-values-with-units",
    "project-agents-writer",
    "project-changelog-writer",
    "project-readme-writer",
    "project-semantic-versioning",
    "project-structure",
    "style-guide-capitalization",
    "style-guide-briefness-style",
    "style-guide-good-writing",
    "continue-behavior",
]


MD_FILENAME2SKILL_NAME = {
    "abbr-currency-symbols": "Abbr Currency Symbols",
    "abbr-emoji": "Abbr Emoji",
    "abbr-natural-language-codes": "Abbr Natural Language Codes",
    "abbr-prefixes": "Abbr Prefixes",
    "abbr-programming-language-codes": "Abbr Programming Language Codes",
    "abbr-single-character": "Abbr Single Character",
    "abbr-starts-with-a": "Abbr Starts with A",
    "abbr-starts-with-b": "Abbr Starts with B",
    "abbr-starts-with-c": "Abbr Starts with C",
    "abbr-starts-with-d": "Abbr Starts with D",
    "abbr-starts-with-digits": "Abbr Starts with Digits 0~9",
    "abbr-starts-with-e": "Abbr Starts with E",
    "abbr-starts-with-f": "Abbr Starts with F",
    "abbr-starts-with-g": "Abbr Starts with G",
    "abbr-starts-with-h": "Abbr Starts with H",
    "abbr-starts-with-i": "Abbr Starts with I",
    "abbr-starts-with-k": "Abbr Starts with K",
    "abbr-starts-with-l": "Abbr Starts with L",
    "abbr-starts-with-m": "Abbr Starts with M",
    "abbr-starts-with-n": "Abbr Starts with N",
    "abbr-starts-with-non-alphanumeric": "Abbr Starts with Non-Alphanumeric",
    "abbr-starts-with-o": "Abbr Starts with O",
    "abbr-starts-with-p": "Abbr Starts with P",
    "abbr-starts-with-q": "Abbr Starts with Q",
    "abbr-starts-with-r": "Abbr Starts with R",
    "abbr-starts-with-s": "Abbr Starts with S",
    "abbr-starts-with-t": "Abbr Starts with T",
    "abbr-starts-with-u": "Abbr Starts with U",
    "abbr-starts-with-v": "Abbr Starts with V",
    "abbr-starts-with-w": "Abbr Starts with W",
    "abbr-starts-with-x": "Abbr Starts with X",
    "abbr-starts-with-y": "Abbr Starts with Y",
    "abbr-suffixes": "Abbr Suffixes",
    "abbr-symbols": "Abbr Symbols",
    "abbr-units-of-measure": "Abbr Units of Measure",
    "annotation-markers": "Annotation Markers",
    "chat": "Chat",
    "coder-bash": "Coder Bash",
    "coder-c": "Coder C",
    "coder-c-sharp": "Coder C Sharp",
    "coder-cpp": "Coder CPP",
    "coder-gdscript": "Coder GDScript",
    "coder-html": "Coder HTML",
    "coder-javascript-and-typescript": "Coder JavaScript and TypeScript",
    "coder-python": "Coder Python",
    "coder-python-docstring-style": "Coder Python Docstring Style",
    "coder-python-testing-guidelines": "Coder Python Testing Guidelines",
    "coder-unity-engine": "Coder Unity Engine",
    "coder-unreal-engine": "Coder Unreal Engine",
    "date-and-time-format": "Date and Time Format",
    "kaye-peer-coder": "Kaye Peer Coder",
    "numerical-values-with-units": "Numerical Values with Units",
    "project-agents-writer": "Project AGENTS Writer",
    "project-changelog-writer": "Project CHANGELOG Writer",
    "project-readme-writer": "Project README Writer",
    "project-semantic-versioning": "Project Semantic Versioning",
    "project-structure": "Project Structure",
    "style-guide-capitalization": "Style Guide Capitalization",
    "style-guide-briefness-style": "Style Guide Briefness Style",
    "style-guide-good-writing": "Style Guide Good Writing",
    "continue-behavior": "Continue Behavior",
}


PROMPT_FILENAMES = [
    "create-agents",
    "create-readme",
    "maintain-changelog",
    "maintain-docs",
    "prepare-for-feature",
    "prepare-for-release",
    "resolve-annotation-markers",
]


PROMPT_FILENAME2NAME = {
    "create-agents": "create_agents.md",
    "create-readme": "create_readme.md",
    "maintain-changelog": "maintain_changelog.md",
    "maintain-docs": "maintain_docs.md",
    "prepare-for-feature": "prepare_for_feature_finish.md",
    "prepare-for-release": "prepare_for_release.md",
    "resolve-annotation-markers": "resolve_annotation_markers.md",
}
