MD_FILENAMES = [
    "annotation-markers",
    "chat",
    "coder-bash",
    "coder-c",
    "coder-c-sharp",
    "coder-cpp",
    "coder-gdscript",
    "coder-html",
    "coder-javascript-and-typescript",
    "coder-python",
    "coder-python-docstring-style",
    "coder-python-testing-guidelines",
    "coder-unity-engine",
    "coder-unreal-engine",
    "date-and-time-format",
    "kaye-peer-coder",
    "numerical-values-with-units",
    "project-agents-writer",
    "project-changelog-writer",
    "project-readme-writer",
    "project-semantic-versioning",
    "project-structure",
    "style-guide-capitalization",
    "style-guide-briefness-style",
    "style-guide-good-writing",
]


MD_FILENAME2SKILL_NAME = {
    "annotation-markers": "Annotation Markers",
    "chat": "Chat",
    "coder-bash": "Coder Bash",
    "coder-c": "Coder C",
    "coder-c-sharp": "Coder C Sharp",
    "coder-cpp": "Coder CPP",
    "coder-gdscript": "Coder GDScript",
    "coder-html": "Coder HTML",
    "coder-javascript-and-typescript": "Coder JavaScript and TypeScript",
    "coder-python": "Coder Python",
    "coder-python-docstring-style": "Coder Python Docstring Style",
    "coder-python-testing-guidelines": "Coder Python Testing Guidelines",
    "coder-unity-engine": "Coder Unity Engine",
    "coder-unreal-engine": "Coder Unreal Engine",
    "date-and-time-format": "Date and Time Format",
    "kaye-peer-coder": "Kaye Peer Coder",
    "numerical-values-with-units": "Numerical Values with Units",
    "project-agents-writer": "Project AGENTS Writer",
    "project-changelog-writer": "Project CHANGELOG Writer",
    "project-readme-writer": "Project README Writer",
    "project-semantic-versioning": "Project Semantic Versioning",
    "project-structure": "Project Structure",
    "style-guide-capitalization": "Style Guide Capitalization",
    "style-guide-briefness-style": "Style Guide Briefness Style",
    "style-guide-good-writing": "Style Guide Good Writing",
}
