[metadata]
name = Prompt Engineering Project Kaye
version = 6.5.2-alpha
description = Define Kaye, a devoted and deferential AI assistant persona, in a single source of truth and reuse it consistently across every task and tool
long_description = file: README.md
author = kamiLeL
author_email = 77594253+kami-lel@users.noreply.github.com
home_page = https://github.com/kami-lel/kaye/blob/main/README.md
project_urls =
    Repository = https://github.com/kami-lel/kaye

[options]
include_package_data = True
packages = find:
package_dir =
    = .

python_requires = >=3.11
install_requires =
    anytree
    flask
    pyahocorasick
    pydantic
    pyyaml


[options.package_data]
* =
    prompt_corpus.md
    abbrs.json
