[metadata]
name = Kaye
version = 4.8.2-alpha
description = Prompt Engineering Project Kaye
long_description = file: README.md
author = kamiLeL

[options]
include_package_data = True
packages = find:
package_dir =
    = .

install_requires =
    anytree
    pyyaml

[options.package_data]
* =
    prompt_corpus.md
    gen_prompt/prompt_blueprints/*
