"""
shared fixtures for ``kaye claude user-system-prompt`` tests
"""

from tests import (
    TESTEE_INTRODUCTION_CONTENT,
    TESTEE_MARKDOWN_FORMAT_CONTENT,
    TESTEE_CHAT_ADDITIONAL_CONTENT,
    TESTEE_CHAT_COMMENTARY_CASE_CONTENT,
    TESTEE_CODER_CONTENT,
)

__all__ = (
    "TESTEE_INTRODUCTION_CONTENT",
    "TESTEE_MARKDOWN_FORMAT_CONTENT",
    "TESTEE_CHAT_ADDITIONAL_CONTENT",
    "TESTEE_CHAT_COMMENTARY_CASE_CONTENT",
    "TESTEE_CODER_CONTENT",
)
