#!/bin/bash

set -euo pipefail

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/set_environment_variable.sh"
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../hooks_utility/hooks_utility.sh"

# start pre-commit checks  #####################################################
echo "pre-commit" | hooks_utility_enter

hooks_utility_debug_commit_type

# ensure file modification  ----------------------------------------------------
# make sure CHANGELOG.md is edited when finish feature branch
hooks_utility_ensure_changelog_edited 'CHANGELOG.md'

# make sure version is bumped when finish feature branch
hooks_utility_ensure_version_updated

# ensure Dify Apps' .yml files are updated
hooks_utility_ensure_changelog_edited 'dify_studio/kaye_cash_tracker/Kaye_Cash_Tracker.yml'
hooks_utility_ensure_changelog_edited 'dify_studio/kaye_commit_sense/Kaye_Commit_Sense.yml'
hooks_utility_ensure_changelog_edited 'dify_studio/kaye_event_radar/Kaye_Event_Radar.yml'
hooks_utility_ensure_changelog_edited 'dify_studio/kaye_peer_coder/Kaye_Peer_Coder.yml'

# perform branch protection  ---------------------------------------------------
hooks_utility_protect_branch

# finish pre-commit checks  ####################################################
echo "pre-commit" | hooks_utility_pass

exit 0
